color0 #26292c
color1 #fd4663
color2 #9fa6ac
color3 #9fa3ac
color4 #9fa0ac
color5 #bbc0c4
color6 #bbbdc4
color7 #f2f2f3
color8 #656a6d
color9 #fd4663
color10 #9fa6ac
color11 #9fa3ac
color12 #9fa0ac
color13 #bbc0c4
color14 #bbbdc4
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c1f21
background            #1c1f21
foreground            #f2f2f3
selection_foreground  #b0b3b5
selection_background  #26292c
active_border_color   #9fa6ac
inactive_border_color #26292c
url_color             #9fa6ac

active_tab_foreground   #1c1f22
active_tab_background   #9fa6ac
inactive_tab_foreground #b0b3b5
inactive_tab_background #26292c
cursor_trail_color      #b0b3b5
